package com.github.nicolasholanda.newspaper.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;


@Getter
@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "news")
public class News {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String newsId;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private LocalDateTime createdAt = LocalDateTime.now();

    @DynamoDBAttribute
    private User author;
}
